### ISSUE TITLE
Create new service in InciManagement in order to send Incidences constantly

### ISSUE THREAD

**Issue by adrian-demig-pal** [Arquisoft/Inci_i3b#24]
Create a new service in order to send Incidents to Kafka, e.g every 20 seconds.

**Comment by sergiosantano** [comment]
Format of the temperature sensor incidences:

Title: Temperature Alert 
Description: Temperature alert from sensor _sensorname_

Add one custom field:
Field name: temp
Value: X (Where X is an integer between 0 and 40. An alert must be shown if the temperature is below 10 or over 30)
