### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by sergiosantano** [Arquisoft/Inci_i3b#29]
In this issue it´s explained all the work that must be done before Monday 7th at night. After doing each task, the student will add a comment in order to inform the rest of team his part is done. The tasks that must be done:

- [x] - Usability and Accessibility QA: @JorgeGarciaMarin and me
- [x] - Add technical constraints to the views: @JorgeGarciaMarin and me
- [x] - Check each constraint and QA has a scenario: @Victorreme y @alfredofuentes9 
- [x] - Review new diagrams in paragraph 7: Everybody
- [x] - Update names in documentation according to the code: Each subteam its module.
- [x] - Update diagram InciManagement: @alfredofuentes9 
- [x] - Update diagram Dashboard: me
- [x] - Update diagram Context: @Victorreme 
- [x] - Update context view information and add relational (paragraph 9): @Victorreme and @alfredofuentes9 
- [x] - Review all the views after being modified: Everybody
- [x] - Check all the QA appears at least in one view: @admipa97 
- [x] - Package View: @JorgeGarciaMarin and me
- [x] - Deployment View: @admipa97

**Comment by sergiosantano** [comment]
Usability and Accessibility QA: added

**Comment by sergiosantano** [comment]
Technical constraints added to the views and rationales

**Comment by sergiosantano** [comment]
Dashboard names modified

**Comment by sergiosantano** [comment]
Dashboard view updated

**Comment by Victorreme** [comment]
InciManagement and Context diagrams updated

**Comment by Victorreme** [comment]
Context view updated and rationale added

**Comment by adrian-demig-pal** [comment]
Deployment view created
